### PR TITLE
Fix LMIC_disableChannel for CFG_us915

### PR DESCRIPTION
**Pull request by frankleonrose**
https://github.com/matthijskooijman/arduino-lmic/issues/8

### CODE REVIEW

**Comment by kgbvax** [comment]
To what extend is this CFG_us915 specific?

**Comment by frankleonrose** [comment]
The bug is in the version of LMIC_disableChannel that is under #elif
defined(CFG_us915)

There is another implementation above under #if defined eu

**Comment by frankleonrose** [comment]
@matthijskooijman One line fix. Same as https://github.com/tftelkamp/arduino-lmic-v1.5/commit/b307c9a6dc389a00d20626cfb78719406b650f12#diff-f6cd8245a05bdce4952f0f47026fe225L764

**Comment by matthijskooijman** [comment]
IBM is intending to change the license on the LMIC library to [the three-clause BSD license](https://opensource.org/licenses/BSD-3-Clause). To simplify incorporating your contribution upstream on the next LMIC release, would you be willing to license it under the same license? If so, please explicitly state this in a comment to this PR? Saying something like "This contribution is licensed under the terms of the three-clause BSD license, as linked above" should be sufficient.

**Comment by frankleonrose** [comment]
This contribution is licensed under the terms of the three-clause BSD license, as linked above.

**Comment by hallard** [comment]
This contribution is licensed under the terms of the three-clause BSD license, as linked above

**Comment by matthijskooijman** [comment]
I merged this PR manually (to rebase it and remove an unrelated whitespace change).

**Comment by frankleonrose** [comment]
Sorry you had to do it manually. I'll exclude the whitespace changes in the future. Thanks for accepting.

**Comment by matthijskooijman** [comment]
No problem! Manually merging is often better anyway, to get a somewhat more linear history in the face of multiple parallel pullrequests :-)

**Comment by matthijskooijman** [comment]
(also, I need to pull the commits before merging anyway to test them, so manual merging isn't really more work :-p)

**Pull request closed without merging**
