### PR TITLE
Add AU915 bandwidth and Adafruit Feather LoRa Boards

### PR DESCRIPTION
**Pull request by testert1ng**
Extend most of the US915 configurations, changed frequencies for TX and RX.

### CODE REVIEW

**Review by StereotypicalSquirrel — CHANGES_REQUESTED** [review]
I have successfully tested this merge on an Adafruit Adafruit Feather M0 RFM95 LoRa on AU915. ABP and OTAA both work with TTN.

I recommend the following changes:
1. Line 239 has a typo (Adfruit).
2. Line 249 has a typo (boadr).
3. Add either a pinmap or a comment for the Adfruit Feather M0 RFM95.

Correct pinmap for the M0 version is (Only difference is that DIO0 changes to pin 3):

#### Adafruit Feather M0 RFM95W loRa Radio 900MHz
This board uses the following pin mapping:

    const lmic_pinmap lmic_pins = {
    	.nss = 8,
    	.rxtx = LMIC_UNUSED_PIN,
    	.rst = 4,
    	.dio = {3, 6, LMIC_UNUSED_PIN},
	};

**PIN6** and **IO1** from the Adafruit board need to be connected before uploading the code.

Thanks

**Comment by testerting** [comment]
@StereotypicalSquirrel Thanks for your suggestion. 

I have fixed the problems and added M0 pin map.

**Comment by ElectronicallyE** [comment]
Could this please be merged? I've been using this branch as my primary library for over a month and it works perfectly with no issues. Being in Australia, the standard library does not work for AU915, meaning I have had to resort to using the code by @testerting

**Review by atglira — APPROVED** [review]

**Comment by matthijskooijman** [comment]
This repository is now deprecated, see #297 for some more background. I'm grateful for your contribution, but it will no longer be merged. I'm recommending people to use the [MCCI version of LMIC](https://github.com/mcci-catena/arduino-lmic) instead. If this PR addresses an issue that also exists in that version, I would encourage you to resubmit your contribution there, so it might benefit other users. I'm sorry for the inconvenience...

**Pull request closed without merging**
