### PR TITLE
Conditionally compile regional code in examples

### PR DESCRIPTION
**Pull request by frankleonrose**

### CODE REVIEW

**Comment by matthijskooijman** [comment]
IBM is intending to change the license on the LMIC library to [the three-clause BSD license](https://opensource.org/licenses/BSD-3-Clause). To simplify incorporating your contribution upstream on the next LMIC release, would you be willing to license it under the same license? If so, please explicitly state this in a comment to this PR? Saying something like "This contribution is licensed under the terms of the three-clause BSD license, as linked above" should be sufficient.

**Comment by frankleonrose** [comment]
This contribution is licensed under the terms of the three-clause BSD license, as linked above.

**Comment by hallard** [comment]
This contribution is licensed under the terms of the three-clause BSD license, as linked above

**Comment by matthijskooijman** [comment]
Thanks!

**Pull request merged**
